name: Secrets Workflow

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  Linux-Secrets-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Bash syntax example 1
        with:
          super_secret: ${{ secrets.MySecret }}
        env: 
          super_secret: ${{ secrets.MySecret }}
        run:
          echo "$SUPER_SECRET"

  Linux-Secrets-2:
    runs-on: ubuntu-latest
    steps:
      - name: YAML Bash syntax example 2
        env:
          super_secret: ${{ secrets.MySecret }}
        run: |
          echo "$SUPER_SECRET"
