name: Linux Secrets Workflow

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  Linux-Secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Bash syntax example 1
        env: 
          SUPER_SECRET: ${{ secrets.MYSECRET }}
        run:
          echo $SUPER_SECRET
