name: Secrets Workflow

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  secret1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Linux syntax example 
        with:
          super_secret: ${{ secrets.MySecret }}
        env: 
          super_secret: ${{ secrets.MySecret }}
        run:
          echo "$SUPER_SECRET"
  secret2:
    runs-on: ubuntu-latest
    steps:
      - name: Linux 
        env:
          super_secret: ${{ secrets.MySecret }}
        run: |
          echo "$SUPER_SECRET"

