name: Linux Secrets Workflow

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  Linux-Secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Bash syntax example 1
        env: 
          SUPER_SECRET: ${{ secrets.MYSECRET }}
        run:
          echo $SUPER_SECRET
          
  Windows-Secrets:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Powershell syntax Example
        env:
          SUPER_SECRET: ${{ secrets.MYSECRET }}
          run:
            echo $env:SUPER_SECRET