name: Workflow One

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ] 
  workflow_dispatch:

jobs:
  One-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a two-line script
        run: |
          echo Welcome to my multiline step
          echo This is my first workflow
          
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo this commands run inside the shell of the runner
