name: Secrets Workflow

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML syntax example 
        with:
          super_secret: ${{ secrets.MySecret }}
        env: 
          super_secret: ${{ secrets.MySecret }}
    secret2:
      runs-on: ubuntu-latest
        env:
          super_secret: ${{ secrets.MySecret }}
          run: |
            echo "$SUPER_SECRET"
    secrets3:
      runs-on: windows-latest
        env:
          super_secret: ${{ secrets.MySecret }}
          run: |
            echo "$env:SUPER_SECRET"
