name: Workflow Two

on: 
  pull_request:
    branches: [staging, main]
  push:
    branches: [staging, main]
  workflow_dispatch:

    jobs:
      job-one:

      job-two:
        needs: job-one

      job-three:
        needs: [job-one, job-two]

 