name: Windows Secrets Workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  Windows-Secrets:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: YAML Powershell syntax Example
        env:
          SUPER_SECRET: ${{ secrets.MYSECRET }}
          run:
            echo $env:SUPER_SECRET
