name: Windows Github Hosted Runner workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  Windows-Secrets:
    runs-on: windows-latest

    steps:
      - name: YAML Powershell syntax Example
        env:
          super_secret: ${{ secrets.MySecret }}
          run: |
            echo "$env:SUPER_SECRET"
